#!/usr/bin/env bash
set -euo pipefail

# shellcheck disable=SC1091
[[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

rustc --version
cargo --version
node --version
npm --version
bun --version
